platform: linux

image_resource:
  type: docker-image
  source:
    repository: steeltoeoss/behave

inputs:
  - name: Samples

outputs:
  - name: logs

params:
  FEATURES: .
  LOGFILE: behave.log
  MAX_ATTEMPTS: 60
  CF_MAX_ATTEMPTS: 120

run:
  path: Samples/ci/scripts/behave.sh
