resources:

  - name: cfg-cloudfoundry-src
    type: git
    source:
      uri: https://github.com/SteeltoeOSS/Samples
      branch: dev
      paths:
        - Configuration/src/AspDotNetCore/CloudFoundry

  - name: cfg-simple-src
    type: git
    source:
      uri: https://github.com/SteeltoeOSS/Samples
      branch: dev
      paths:
        - Configuration/src/AspDotNetCore/Simple

  - name: cfg-simplecloudfoundry-src
    type: git
    source:
      uri: https://github.com/SteeltoeOSS/Samples
      branch: dev
      paths:
        - Configuration/src/AspDotNetCore/SimpleCloudFoundry

  - name: cnn-mysql-src
    type: git
    source:
      uri: https://github.com/SteeltoeOSS/Samples
      branch: dev
      paths:
        - Connectors/src/AspDotNetCore/MySql

  - name: cnn-redis-src
    type: git
    source:
      uri: https://github.com/SteeltoeOSS/Samples
      branch: dev
      paths:
        - Connectors/src/AspDotNetCore/Redis

jobs:

  - name: cfg-cloudfoundry
    plan:
      - get: Samples
        resource: cfg-cloudfoundry-src
        trigger: true
      - task: behave
        file: Samples/ci/tasks/behave.yml
        params:
          FEATURES: Configuration/src/AspDotNetCore/CloudFoundry
          CF_APIURL: {{cf_apiurl}}
          CF_USERNAME: {{cf_username}}
          CF_PASSWORD: {{cf_password}}
          CF_ORG: {{cf_org}}
        on_failure:
          task: behavelog
          file: Samples/ci/tasks/showlog.yml

  - name: cfg-simple
    plan:
      - get: Samples
        resource: cfg-simple-src
        trigger: true
      - task: behave
        file: Samples/ci/tasks/behave.yml
        params:
          FEATURES: Configuration/src/AspDotNetCore/Simple
        on_failure:
          task: behavelog
          file: Samples/ci/tasks/showlog.yml

  - name: cfg-simplecloudfoundry
    plan:
      - get: Samples
        resource: cfg-simplecloudfoundry-src
        trigger: true
      - task: behave
        file: Samples/ci/tasks/behave.yml
        params:
          FEATURES: Configuration/src/AspDotNetCore/SimpleCloudFoundry
          CF_APIURL: {{cf_apiurl}}
          CF_USERNAME: {{cf_username}}
          CF_PASSWORD: {{cf_password}}
          CF_ORG: {{cf_org}}
        on_failure:
          task: behavelog
          file: Samples/ci/tasks/showlog.yml

  - name: cnn-mysql
    plan:
      - get: Samples
        resource: cnn-mysql-src
        trigger: true
      - task: behave
        file: Samples/ci/tasks/behave.yml
        params:
          FEATURES: Connectors/src/AspDotNetCore/MySql
          CF_APIURL: {{cf_apiurl}}
          CF_USERNAME: {{cf_username}}
          CF_PASSWORD: {{cf_password}}
          CF_ORG: {{cf_org}}
        on_failure:
          task: behavelog
          file: Samples/ci/tasks/showlog.yml

  - name: cnn-redis
    plan:
      - get: Samples
        resource: cnn-redis-src
        trigger: true
      - task: behave
        file: Samples/ci/tasks/behave.yml
        params:
          FEATURES: Connectors/src/AspDotNetCore/Redis
          CF_APIURL: {{cf_apiurl}}
          CF_USERNAME: {{cf_username}}
          CF_PASSWORD: {{cf_password}}
          CF_ORG: {{cf_org}}
        on_failure:
          task: behavelog
          file: Samples/ci/tasks/showlog.yml

groups:

  - name: cfg
    jobs:
      - cfg-cloudfoundry
      - cfg-simple
      - cfg-simplecloudfoundry

  - name: cnn
    jobs:
      - cnn-mysql
      - cnn-redis
